prompt_execute "sudo ss -tunlp #check the open doors"
prompt_execute "ip a #your current address"
prompt_execute "sudo nano /etc/network/interfaces"
prompt_execute "change line allow-hotplug enp0s3 to"
prompt_execute "auto enp0s3"
prompt_execute "change line iface enp0s3 inet dhcp to"
prompt_execute "iface enp0s3 inet static"
prompt_execute "Then add the follow lines"
prompt_execute "address your_current_ip"
prompt_execute "netmask 255.255.0.0"
prompt_execute "gateway 10.11.254.254"
prompt_execute "dns-nameservers 10.11.254.254"
prompt_execute "sudo systemctl restart networking"
prompt_execute "sudo systemctl status networking"
prompt_execute "sudo reboot"
prompt_execute "ss -tulnp"