prompt_execute "sudo systemctl status ssh"
prompt_execute "sudo nano /etc/ssh/sshd_config"
prompt_execute "Find this line #Port22 to Port 4242 && sudo grep Port /etc/ssh/sshd_config"
prompt_execute "sudo service ssh restart"
prompt_execute "sudo ufw enable"
prompt_execute "sudo ufw status numbered"
prompt_execute "sudo ufw allow ssh"
prompt_execute "sudo ufw allow 4242"
prompt_execute "sudo ufw status numbered"
prompt_execute "Change the Host Port and Guest Port to 4242 in Oracle VM"
prompt_execute "sudo systemctl restart ssh"
prompt_execute "Restart the VM"
prompt_execute "In Ubuntu terminal"
prompt_execute "ssh wcorrea-@127.0.0.1 -p 4242"
prompt_execute "If get any error in the connection"
prompt_execute "rm ~/.ssh/known_hosts"
prompt_execute "change the Network config to attached to bridge adaptor - eno2"